pipeline:
  build:
    image: golang
    commands:
      - go build
      - go test

  notify:
    image: plugins/slack
    channel: code
      when:
      event: [ success, failure, push, tag, deployment, pull_request ]
