app:
  path: http://testtest.twreporter.org:8888
  token: YOUR_AUTH_TOKEN

db:
  name:     test_membership
  user:     root
  password: test
  address:  127.0.0.1
  port:     3306

oauth:
  facebook:
    id: YOUR_CLIENT_ID
    secret: YOUR_CLIENT_SECRET
    url: http://testtest.twreporter.org:8080/v1/auth/facebook/callback
    statestr: thisshouldberandom
